export const initialStudentProfile = {
  id: "student-uuid-1",
  fullName: "Alex Sharma",
  email: "alex.sharma@student.edu",
  rollNumber: "CS2023001",
  department: "Computer Science",
  cgpa: 8.85,
  tenthPercentage: 94.2,
  twelfthPercentage: 92.5,
  activeBacklogs: 0,
  skills: ["React", "Node.js", "PostgreSQL", "Python", "Docker", "AWS"],
  resumeUrl: "https://drive.google.com/sample-resume-alex.pdf",
  phone: "+91 98765 43210",
};

export const initialDrives = [
  {
    id: "drive-1",
    title: "Software Development Engineer - I",
    companyName: "Google",
    description: "Join Google Cloud team to build next-generation enterprise interfaces and scalable distributed cloud systems. Looking for engineers passionate about data structures, high concurrency, and clean code.",
    ctc: "32 LPA",
    location: "Bangalore / Hyderabad, India",
    minCgpa: 8.0,
    allowedBranches: ["Computer Science", "Information Technology"],
    maxBacklogs: 0,
    deadline: new Date(Date.now() + 8 * 24 * 60 * 60 * 1000).toISOString(),
    createdByName: "Google Recruitment Cell",
    tags: ["Full-Time", "Cloud & Infra", "Tier 1"],
    applicantsCount: 42,
  },
  {
    id: "drive-2",
    title: "Graduate Software Engineer (Azure / AI)",
    companyName: "Microsoft",
    description: "Work on Azure distributed platforms, OpenAI model integration pipelines, and high-performance computing services across cross-functional engineering teams.",
    ctc: "28 LPA",
    location: "Hyderabad, India",
    minCgpa: 7.5,
    allowedBranches: ["Computer Science", "Information Technology", "Electronics"],
    maxBacklogs: 0,
    deadline: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString(),
    createdByName: "Microsoft University Relations",
    tags: ["AI/ML", "Cloud Systems", "Tier 1"],
    applicantsCount: 68,
  },
  {
    id: "drive-3",
    title: "Systems & Infrastructure Engineer",
    companyName: "Amazon",
    description: "Architect resilient AWS services, event-driven pipelines, and distributed databases for high-throughput global e-commerce systems.",
    ctc: "26 LPA",
    location: "Chennai / Bangalore, India",
    minCgpa: 7.0,
    allowedBranches: ["Computer Science", "Information Technology", "Electronics", "Electrical"],
    maxBacklogs: 1,
    deadline: new Date(Date.now() + 12 * 24 * 60 * 60 * 1000).toISOString(),
    createdByName: "Amazon Talent Acquisition",
    tags: ["Backend", "Distributed Systems", "Tier 1"],
    applicantsCount: 89,
  },
  {
    id: "drive-4",
    title: "Associate Technology Analyst",
    companyName: "Goldman Sachs",
    description: "Develop quantitative models, real-time trade settlement engines, and algorithmic risk computing microservices in our global markets engineering division.",
    ctc: "24 LPA",
    location: "Bangalore, India",
    minCgpa: 7.5,
    allowedBranches: ["Computer Science", "Information Technology", "Mathematics & Computing"],
    maxBacklogs: 0,
    deadline: new Date(Date.now() + 15 * 24 * 60 * 60 * 1000).toISOString(),
    createdByName: "Goldman Sachs Campus Team",
    tags: ["FinTech", "High-Frequency", "Core"],
    applicantsCount: 35,
  },
];

export const initialApplications = [
  {
    id: "app-1",
    jobDriveId: "drive-1",
    companyName: "Google",
    title: "Software Development Engineer - I",
    ctc: "32 LPA",
    status: "SHORTLISTED",
    appliedAt: "2026-08-28T14:30:00Z",
    location: "Bangalore / Hyderabad, India",
    roundDetails: "Technical Screening Round 1 scheduled on Sept 2, 2026",
  },
  {
    id: "app-2",
    jobDriveId: "drive-2",
    companyName: "Microsoft",
    title: "Graduate Software Engineer (Azure / AI)",
    ctc: "28 LPA",
    status: "APPLIED",
    appliedAt: "2026-08-29T10:15:00Z",
    location: "Hyderabad, India",
    roundDetails: "Application under resume review by recruiter",
  },
];

export const initialAdminStats = {
  totalOffers: 142,
  placedStudents: 138,
  activeDrives: 18,
  averagePackage: "18.6 LPA",
  highestPackage: "48.0 LPA",
  placementRate: "94.2%",
  topRecruiters: [
    { name: "Google", offers: 14, avgCtc: "32 LPA" },
    { name: "Microsoft", offers: 22, avgCtc: "28 LPA" },
    { name: "Amazon", offers: 31, avgCtc: "26 LPA" },
    { name: "Goldman Sachs", offers: 12, avgCtc: "24 LPA" },
  ],
};
